spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/image_processor
    username: root
    password: Something@123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    web: info

