spring:
  datasource:
    url: jdbc:mysql://sql12.freemysqlhosting.net/sql12363078
    username: sql12363078
    password: m1Asnul1PQ
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    web: info

