spring:
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-node: localhost:9200
      repository:
        enable : true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/image_processor
    username: root
    password: Something@123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        validator:
          apply_to_ddl:true
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    web: info
folder:
  location: Images
  compress: ResponseFolder

